### ISSUE TITLE
Internal Server Error after installing ThePoser

### ISSUE THREAD

**Issue by JulianMartinez** [mantisbt-plugins/ThePoser#2] opened 2014-07-03 15:46 UTC
In my company we have Mantis running in our machine. Version is 1.2.5 and Schema is 183.
I followed Installation instructions and when I clicked on Install, browser went to white.
Using Firebug I realized that Error 500 was raised.

Any idea?

**Comment by snowyurik** [comment] 2014-07-04 02:06
Can you check server error log for error message and post it here?

**Comment by snowyurik** [comment] 2014-07-04 02:13
Btw, It you need your Mantis back to work asap you can disable ThePoser with this sql query:
DELETE FROM mantis_plugin_table  WHERE basename='ThePoser' LIMIT 1;

However, it will be good if we can find out what happened, and so i'll fix the bug.

**Comment by snowyurik** [comment] 2014-07-04 02:34
Just a guess: then you download zip from github you get archive with ThePoser-master folder inside, containing readme etc and ThePoser folder, it is possible if you copied entire ThePoser-master folder into plugins folder?

**Comment by snowyurik** [comment] 2014-07-06 08:57
Well, i'm not able to reproduce it on latest version, and no details from Julian, so i'll close this issue for now. Feel free to open a new one.

**Closed as completed by snowyurik** 2014-07-06 08:57 UTC

**Comment by JulianMartinez** [comment] 2014-07-07 14:20
Hello wnowyurik. Excuse I didn't reply before.. I have uploaded a piece of the log in following link: http://mural.uv.es/jumaru/error_log.txt

I hope we can clarify the reason I was not able to install the pluggin.
Thanks
